Repository Rome-Squad/CineVerse-App, pull requests merged in 2025-08, with the labels that each got.

#471 fix: Add TikTok and Twitter social media links
  datasource/remote/media/src/main/java/com/giraffe/media/person/retrofit/PersonApiServiceRetrofit.kt
  domain/media/src/main/java/com/giraffe/media/person/entity/PersonSocialMediaLinks.kt
  presentation/details/src/main/java/com/giraffe/details/components/MainDetails.kt
  presentation/details/src/main/java/com/giraffe/details/components/gallery/GalleryItem.kt
  presentation/details/src/main/java/com/giraffe/details/components/gallery/GalleryItemLayout.kt
  presentation/details/src/main/java/com/giraffe/details/screens/castDetails/CastDetailsInteractionListener.kt
  presentation/details/src/main/java/com/giraffe/details/screens/castDetails/CastDetailsScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/castDetails/CastDetailsUiState.kt
  presentation/details/src/main/java/com/giraffe/details/screens/castDetails/CastDetailsViewModel.kt
  presentation/details/src/main/res/values-ar-rEG/strings.xml
  presentation/details/src/main/res/values/strings.xml
  repository/media/src/main/java/com/giraffe/media/person/datasource/remote/dto/PersonSocialMediaDto.kt
  repository/media/src/main/java/com/giraffe/media/person/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/utils/UrlConstants.kt
Labels: bug

#488 Fix/home screen crash when no internet
  presentation/home/src/main/java/com/giraffe/home/base/BaseViewModel.kt
  presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt
Labels: bug

#492 Refactor: Improve date formatting and genre display in Discover screen
  presentation/explore/src/main/java/com/giraffe/explore/screen/discover/DiscoverViewModel.kt
  presentation/explore/src/main/java/com/giraffe/explore/util/Mapper.kt
Labels: fix

#491 Refactor: Streamline search results and improve error handling
  datasource/local/media/src/main/java/com/giraffe/media/series/dao/SeriesDao.kt
  domain/media/src/main/java/com/giraffe/media/movies/usecase/SearchMovieByNameUseCase.kt
  domain/media/src/main/java/com/giraffe/media/series/usecase/SearchSeriesByNameUseCase.kt
  presentation/explore/src/main/java/com/giraffe/explore/base/BaseViewModel.kt
  presentation/explore/src/main/java/com/giraffe/explore/components/TransitionLazyColumnToGrid.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultInteractionListener.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultScreen.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultScreenState.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultViewModel.kt
  presentation/explore/src/main/java/com/giraffe/explore/util/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/movie/MoviesRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/person/PersonRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/series/SeriesRepositoryImpl.kt
Labels: enhancement

#411 Handle Back Press on Home Start Destination to Exit App
  presentation/authentication/src/main/java/com/giraffe/authentication/nav/route/HomeRoute.kt
  presentation/home/src/main/java/com/giraffe/home/navigation/HomeNavGraph.kt
Labels: fix

#496 Create Collections Use Cases & Collections Repository Interface
  domain/media/src/main/java/com/giraffe/media/collections/entity/Collection.kt
  domain/media/src/main/java/com/giraffe/media/collections/repository/CollectionsRepository.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/AddCollectionUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/AddMovieToCollectionUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/AddSeriesToCollectionUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/ClearCollectionUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/GetCollectionDetailsUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/GetCollectionMoviesUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/GetCollectionSeriesUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/GetCollectionsUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/RemoveCollectionUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/RemoveMovieFromCollectionUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/RemoveSeriesFromCollectionUseCase.kt
  domain/media/src/main/java/com/giraffe/media/exception/MediaException.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/fake/createFakeMovie.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/fake/createFakeSeries.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/fake/cretaeFakeCollection.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/AddCollectionUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/AddMovieToCollectionUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/AddSeriesToCollectionUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/ClearCollectionUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/GetCollectionDetailsUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/GetCollectionMoviesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/GetCollectionSeriesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/GetCollectionsUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/RemoveCollectionUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/RemoveMovieFromCollectionUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/RemoveSeriesFromCollectionUseCaseTest.kt
Labels: Component

#501 Implement CollectionsRepository And Add Interface to RemoteDataSource
  app/src/main/java/com/giraffe/cineverseapp/di/repositoryModule.kt
  repository/media/src/main/java/com/giraffe/media/collections/CollectionsRepositoryImp.kt
  repository/media/src/main/java/com/giraffe/media/collections/datasource/remote/CollectionsRemoteDataSource.kt
  repository/media/src/main/java/com/giraffe/media/collections/datasource/remote/dto/CollectionDto.kt
  repository/media/src/main/java/com/giraffe/media/collections/mapper/Mapper.kt
Labels: Component

#517 Implement collections remote data source & remove series from collections
  app/src/main/java/com/giraffe/cineverseapp/di/networkModule.kt
  datasource/remote/media/src/main/java/com/giraffe/media/collections/response/CollectionIdResponse.kt
  datasource/remote/media/src/main/java/com/giraffe/media/collections/response/CollectionItemIdRequestBody.kt
  datasource/remote/media/src/main/java/com/giraffe/media/collections/response/CollectionItemsResponse.kt
  datasource/remote/media/src/main/java/com/giraffe/media/collections/response/CollectionsResponse.kt
  datasource/remote/media/src/main/java/com/giraffe/media/collections/response/DefaultResponse.kt
  datasource/remote/media/src/main/java/com/giraffe/media/collections/retrofit/CollectionsApiServiceRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/collections/retrofit/CollectionsRemoteDataSourceImp.kt
  datasource/remote/media/src/main/java/com/giraffe/media/util/NetworkConstants.kt
  datasource/remote/media/src/main/java/com/giraffe/media/util/RetrofitRequestBuilder.kt
  domain/media/src/main/java/com/giraffe/media/collections/entity/Collection.kt
  domain/media/src/main/java/com/giraffe/media/collections/repository/CollectionsRepository.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/AddSeriesToCollectionUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/GetCollectionSeriesUseCase.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/RemoveSeriesFromCollectionUseCase.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/fake/cretaeFakeCollection.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/AddSeriesToCollectionUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/GetCollectionSeriesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/RemoveSeriesFromCollectionUseCaseTest.kt
  repository/media/src/main/java/com/giraffe/media/collections/CollectionsRepositoryImp.kt
  repository/media/src/main/java/com/giraffe/media/collections/datasource/remote/CollectionsRemoteDataSource.kt
  repository/media/src/main/java/com/giraffe/media/collections/datasource/remote/dto/CollectionDto.kt
  repository/media/src/main/java/com/giraffe/media/collections/datasource/remote/dto/CollectionItemDto.kt
  repository/media/src/main/java/com/giraffe/media/collections/mapper/Mapper.kt
  repository/user/src/main/java/com/giraffe/repository/AuthenticationRepositoryImpl.kt
Labels: Component

#519 Feature/caching series for home screen
  datasource/local/media/src/main/java/com/giraffe/media/series/SeriesRoomLocalDateSource.kt
  datasource/local/media/src/main/java/com/giraffe/media/series/dao/SeriesDao.kt
  datasource/local/media/src/test/java/com/giraffe/media/series/SeriesRoomLocalDateSourceTest.kt
  domain/media/src/main/java/com/giraffe/media/series/repository/SeriesRepository.kt
  domain/media/src/main/java/com/giraffe/media/series/usecase/GetRecentlyReleasedSeriesUseCase.kt
  domain/media/src/main/java/com/giraffe/media/series/usecase/GetRecommendedSeriesUseCase.kt
  domain/media/src/main/java/com/giraffe/media/series/usecase/GetTopRatedSeriesUseCase.kt
  domain/media/src/test/kotlin/com/giraffe/media/series/usecase/GetRecentlyReleasedSeriesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/series/usecase/GetRecommendedSeriesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/series/usecase/GetTopRatedSeriesUseCaseTest.kt
  presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt
  presentation/home/src/main/java/com/giraffe/home/screen/movies_list/MoviesListViewModel.kt
  repository/media/src/main/java/com/giraffe/media/series/SeriesRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/series/datasource/local/SeriesLocalDateSource.kt
  repository/media/src/main/java/com/giraffe/media/series/datasource/local/cacheDto/SeriesCacheDto.kt
  repository/media/src/test/java/com/giraffe/media/series/SeriesRepositoryImplTest.kt
Labels: feature

#516 Fix authentication bugs phase 2
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/giraffe/cineverseapp/MainActivity.kt
  app/src/main/java/com/giraffe/cineverseapp/main/MainActivity.kt
  app/src/main/java/com/giraffe/cineverseapp/main/MainUiState.kt
  app/src/main/java/com/giraffe/cineverseapp/main/MainViewModel.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/login/LoginViewModel.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/nav/AuthenticationNavGraph.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/resetpassword/ResetPasswordWebViewScreen.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/signup/AuthWebViewScreen.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/utils/Constants.kt
  presentation/authentication/src/main/res/values-ar-rEG/strings.xml
  presentation/authentication/src/main/res/values/strings.xml
  presentation/home/src/main/java/com/giraffe/home/components/TopAppBar.kt
  presentation/home/src/main/java/com/giraffe/home/screen/home/HomeScreenUiState.kt
Labels: bug

#533 Create Collection Screen
  presentation/profile/src/main/java/com/giraffe/profile/model/SwipeablePoster.kt
  presentation/profile/src/main/java/com/giraffe/profile/screens/collections/collection/CollectionEffect.kt
  presentation/profile/src/main/java/com/giraffe/profile/screens/collections/collection/CollectionInteractionListener.kt
  presentation/profile/src/main/java/com/giraffe/profile/screens/collections/collection/CollectionRoute.kt
  presentation/profile/src/main/java/com/giraffe/profile/screens/collections/collection/CollectionScreen.kt
  presentation/profile/src/main/java/com/giraffe/profile/screens/collections/collection/CollectionScreenState.kt
  presentation/profile/src/main/java/com/giraffe/profile/screens/collections/collection/CollectionViewModel.kt
  presentation/profile/src/main/res/values-ar/strings.xml
  presentation/profile/src/main/res/values/strings.xml
  repository/media/src/main/java/com/giraffe/media/collections/mapper/Mapper.kt
Labels: feature

#566 Fix Splash Screen Delay
  app/src/main/java/com/giraffe/cineverseapp/main/MainActivity.kt
  app/src/main/java/com/giraffe/cineverseapp/main/MainUiState.kt
  app/src/main/java/com/giraffe/cineverseapp/main/MainViewModel.kt
Labels: fix

#582 Fix/search-result/switch-button-hide
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultScreen.kt
Labels: fix

#587 Refactor: Remove unnecessary join calls in HomeViewModel
  presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt
Labels: fix

#588 Make SettingsScreen scrollable
  presentation/profile/src/main/java/com/giraffe/profile/screens/settings/SettingsScreen.kt
Labels: fix

#592 Fix/details/rating/navigation
  presentation/details/src/main/java/com/giraffe/details/nav/route/LoginRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/MovieDetailsViewModel.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsViewModel.kt
Labels: fix

#594 Refactor: Update rating functionality and UI
  datasource/remote/media/src/main/java/com/giraffe/media/movie/retrofit/MoviesApiServiceRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/series/retrofit/SeriesApiServiceRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/series/retrofit/SeriesRemoteRetrofitDataSourceImp.kt
  datasource/remote/media/src/main/java/com/giraffe/media/util/NetworkConstants.kt
  domain/media/src/main/java/com/giraffe/media/series/repository/SeriesRepository.kt
  domain/media/src/main/java/com/giraffe/media/series/usecase/AddSeriesRatingUseCase.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsViewModel.kt
  presentation/profile/src/main/java/com/giraffe/profile/base/BaseViewModel.kt
  presentation/profile/src/main/java/com/giraffe/profile/screens/ratings/RatingScreen.kt
  presentation/profile/src/main/java/com/giraffe/profile/screens/ratings/RatingViewModel.kt
  repository/media/src/main/java/com/giraffe/media/series/SeriesRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/series/datasource/remote/SeriesRemoteDataSource.kt
Labels: fix

#629 refactor/611-refactor-profile-presentation
  presentation/profile/src/main/java/com/giraffe/presentation/profile/base/BaseViewModel.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/collectiondetails/CollectionDetailsViewModel.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/history/HistoryViewModel.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/mycollections/MyCollectionsViewModel.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/ratings/RatingViewModel.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/settings/SettingsViewModel.kt
Labels: enhancement

#628 Fixhot/Add Keep and Serializable annotations to ShowMoreSectionType
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/show_more/ShowMoreRoute.kt
Labels: bug

#640 Fix series tab in search
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/discover/DiscoverScreen.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/discover/DiscoverViewModel.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/searchresult/SearchResultScreen.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/searchresult/SearchResultViewModel.kt
Labels: fix

#618 refactor home presentation
  app/src/main/java/com/giraffe/cineverseapp/di/presentationModule.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/base/BaseViewModel.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/BaseScreenWithStates.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/Carousel.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/CollectionItem.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/CollectionListSection.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/HorizontalDivider.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/ListSection.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/ListTitleSection.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/PosterHorizontal.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/PosterVertically.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/TransitionLazyColumnToGrid.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/VODItem.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/components/YourCollectionsSections.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/model/FeaturedCollectionUi.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/model/MediaType.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/model/PopularMediaUi.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/model/Poster.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/model/ShowMorePosterUi.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/model/YourCollectionUi.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/home/HomeNavGraph.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/home/routes/CollectionRoute.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/home/routes/HomeRoute.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/home/routes/MovieDetailsRoute.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/home/routes/SeriesDetailsRoute.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/home/routes/ShowMoreRoute.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/home/routes/YourCollectionsRoute.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/main/MainNavGraph.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/main/routes/ExploreRoute.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/main/routes/HomeRoute.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/main/routes/MatchRoute.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/main/routes/ProfileRoute.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/home/HomeEffect.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/home/HomeInteractionListener.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/home/HomeScreen.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/home/HomeScreenState.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/home/HomeUiModel.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/home/HomeViewModel.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/show_more/ShowMoreEffect.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/show_more/ShowMoreInteractionListener.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/show_more/ShowMoreScreen.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/show_more/ShowMoreScreenState.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/show_more/ShowMoreState.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/show_more/ShowMoreStrategy.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/show_more/ShowMoreViewModel.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/utils/EffectListener.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/utils/FormattedDate.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/utils/MapErrorToMessage.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/utils/Mapper.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/utils/ShowToast.kt
Labels: enhancement

#666 Refactor/domain movie test
  domain/media/src/main/java/com/giraffe/media/movie/repository/MovieRepository.kt
  domain/media/src/main/java/com/giraffe/media/movie/usecase/GetMoviesByNameUseCase.kt
  domain/media/src/main/java/com/giraffe/media/movie/usecase/GetRatedMoviesUseCase.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/AddMovieRatingUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/ClearMoviesCacheUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/DeleteMovieRatingUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/DeleteMovieUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetMovieByNameUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetMovieDetailsUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetMovieGenresUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetMovieReviewsUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetMoviesByGenreUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetMoviesGenresUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetPopularityMoviesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetRatedMoviesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetRecentlyReleasedMoviesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetRecentlyViewedMoviesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetRecommendedMovieUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetUpcomingMoviesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetUserMovieRatingUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/dummyData.kt
  repository/media/src/main/java/com/giraffe/media/movie/MovieRepositoryImpl.kt
Labels: enhancement

#678 Add throttleFirst to BaseViewModel
  presentation/authentication/src/main/java/com/giraffe/presentation/authentication/base/BaseViewModel.kt
  presentation/details/src/main/java/com/giraffe/presentation/details/base/BaseViewModel.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/base/BaseViewModel.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/base/BaseViewModel.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/base/BaseViewModel.kt
Labels: enhancement

#690 Fix search text field courser issue
  designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt
  designsystem/src/main/res/values-ar/strings.xml
  designsystem/src/main/res/values/strings.xml
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/discover/DiscoverInteractionListener.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/discover/DiscoverScreen.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/discover/DiscoverViewModel.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/search/SearchInteractionListener.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/search/SearchScreen.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/search/SearchViewModel.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/searchresult/SearchResultInteractionListener.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/searchresult/SearchResultScreen.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/searchresult/SearchResultViewModel.kt
  presentation/explore/src/main/res/values-ar/strings.xml
Labels: bug

#692 Fix not found result screen issue
  designsystem/src/main/java/com/giraffe/designsystem/composable/NoInternetScreen.kt
  designsystem/src/main/res/values-ar/strings.xml
  designsystem/src/main/res/values/strings.xml
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/searchresult/SearchResultScreen.kt
Labels: bug

#696 Refactor/datasource movie
  app/src/main/java/com/giraffe/cineverseapp/data/database/CineVerseDatabase.kt
  app/src/main/java/com/giraffe/cineverseapp/di/localDataSourceModule.kt
  app/src/main/java/com/giraffe/cineverseapp/di/presentationModule.kt
  datasource/local/media/src/main/java/com/giraffe/media/movie/MovieLocalDataSourceImp.kt
  datasource/local/media/src/main/java/com/giraffe/media/movie/MovieLocalDataSourceImpl.kt
  datasource/local/media/src/main/java/com/giraffe/media/movie/dao/MovieDao.kt
  datasource/local/media/src/main/java/com/giraffe/media/movie/mapper/MapperCache.kt
  datasource/remote/media/src/main/java/com/giraffe/media/collections/retrofit/CollectionsApiServiceRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/movie/retrofit/MoviesApiServiceRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/movie/retrofit/MoviesRemoteDataSourceImplRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/series/retrofit/SeriesApiServiceRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/util/NetworkConstants.kt
  domain/media/src/main/java/com/giraffe/media/movie/repository/MovieRepository.kt
  domain/media/src/main/java/com/giraffe/media/movie/usecase/ClearMoviesCacheUseCase.kt
  domain/media/src/main/java/com/giraffe/media/movie/usecase/DeleteRecentlyViewedMovieByIdUseCase.kt
  domain/media/src/main/java/com/giraffe/media/movie/usecase/GetMatchesYourVibeMoviesUseCase.kt
  domain/media/src/main/java/com/giraffe/media/movie/usecase/GetRecommendedMoviesUseCase.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/DeleteMovieUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetMatchesYourVibeMoviesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/GetRecommendedMovieUseCaseTest.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/home/HomeInteractionListener.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/home/HomeScreen.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/home/HomeViewModel.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/show_more/ShowMoreStrategy.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/history/HistoryViewModel.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/settings/SettingsViewModel.kt
  repository/media/src/main/java/com/giraffe/media/movie/MovieRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/local/MoviesLocalDataSource.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/local/cacheDto/MatchesYourVibeMovieCacheDto.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/local/cacheDto/MovieCacheDto.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/local/cacheDto/MovieGenreCacheDto.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/local/cacheDto/PopularMovieCacheDto.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/local/cacheDto/RecentReleasedMovieCacheDto.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/local/cacheDto/RecentlyViewedMovieCacheDto.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/local/cacheDto/UpcomingMovieCacheDto.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/remote/MoviesRemoteDataSource.kt
  repository/media/src/main/java/com/giraffe/media/movie/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/utils/DatabaseConstants.kt
Labels: enhancement

#705 Fix recording in search result screen
  designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/navigation/ExploreNavGraph.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/navigation/routes/SearchResultRoute.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/searchresult/SearchResultEffect.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/searchresult/SearchResultInteractionListener.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/searchresult/SearchResultScreen.kt
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/searchresult/SearchResultViewModel.kt
Labels: bug

#709 Refactor: Rename extension function orEmpty to orZero for Floats
  presentation/details/src/main/java/com/giraffe/presentation/details/utils/extension.kt
  presentation/details/src/main/java/com/giraffe/presentation/details/utils/mappers.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/utils/Extensions.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/utils/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/collections/datasource/remote/dto/CollectionItemDto.kt
  repository/media/src/main/java/com/giraffe/media/collections/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/mapper/ReviewMapper.kt
  repository/media/src/main/java/com/giraffe/media/movie/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/person/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/series/datasource/remote/dto/SeriesDetailsDto.kt
  repository/media/src/main/java/com/giraffe/media/series/datasource/remote/dto/SeriesDto.kt
  repository/media/src/main/java/com/giraffe/media/series/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/utils/Extension.kt
Labels: fix

#766 fix/user-data
  datasource/local/user/src/main/java/com/giraffe/user/AuthenticationLocalDataSourceImpl.kt
  datasource/local/user/src/main/java/com/giraffe/user/datastore/AuthenticationDatastore.kt
  domain/media/src/main/java/com/giraffe/media/collections/usecase/GetCollectionsUseCase.kt
  domain/media/src/main/java/com/giraffe/media/movie/usecase/rate/GetRatedMoviesUseCase.kt
  domain/media/src/main/java/com/giraffe/media/series/usecase/GetRatedSeriesUseCase.kt
  domain/media/src/test/kotlin/com/giraffe/media/collections/usecase/GetCollectionsUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/movie/usecase/rate/GetRatedMoviesUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/series/usecase/GetRatedSeriesUseCaseTest.kt
  domain/user/src/main/java/com/giraffe/user/repository/UserRepository.kt
  domain/user/src/main/java/com/giraffe/user/usecase/GetUserNameUseCase.kt
  domain/user/src/main/java/com/giraffe/user/usecase/GetUserUseCase.kt
  domain/user/src/main/java/com/giraffe/user/usecase/RefreshUserUseCase.kt
  domain/user/src/test/kotlin/com/giraffe/user/dummydata/DummyData.kt
  domain/user/src/test/kotlin/com/giraffe/user/usecase/GetUserNameUseCaseTest.kt
  domain/user/src/test/kotlin/com/giraffe/user/usecase/GetUserUseCaseTest.kt
  domain/user/src/test/kotlin/com/giraffe/user/usecase/RefreshUserUseCaseTest.kt
  presentation/details/src/main/java/com/giraffe/presentation/details/screens/seasons/SeasonsScreen.kt
  presentation/home/src/main/java/com/giraffe/presentation/home/screen/home/HomeViewModel.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/navigation/ProfileNavGraph.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/navigation/routes/EditProfileWebViewRoute.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/navigation/routes/SettingsScreenRoute.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/edit/EditProfileWebViewScreen.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/settings/SettingsInteractionListener.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/settings/SettingsScreen.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/settings/SettingsScreenState.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/settings/SettingsViewModel.kt
  repository/user/src/main/java/com/giraffe/repository/AuthenticationRepositoryImpl.kt
  repository/user/src/main/java/com/giraffe/repository/UserRepositoryImpl.kt
  repository/user/src/main/java/com/giraffe/repository/datasource/local/AuthenticationLocalDataSource.kt
Labels: enhancement

#769 Fix poster genres in history and discover screens
  presentation/explore/src/main/java/com/giraffe/presentation/explore/screen/discover/DiscoverScreen.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/history/HistoryViewModel.kt
Labels: bug, fix

#776 Fix no internet issues in details
  presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditScreen.kt
  presentation/details/src/main/java/com/giraffe/presentation/details/screens/gallery/GalleryInteractionListener.kt
  presentation/details/src/main/java/com/giraffe/presentation/details/screens/gallery/GalleryScreen.kt
  presentation/details/src/main/java/com/giraffe/presentation/details/screens/gallery/GalleryViewModel.kt
  presentation/details/src/main/java/com/giraffe/presentation/details/screens/moviedetails/MovieDetailsScreen.kt
  presentation/details/src/main/java/com/giraffe/presentation/details/screens/seasons/SeasonInteractionListener.kt
  presentation/details/src/main/java/com/giraffe/presentation/details/screens/seasons/SeasonsScreen.kt
  presentation/details/src/main/java/com/giraffe/presentation/details/screens/seasons/SeasonsViewModel.kt
  presentation/details/src/main/java/com/giraffe/presentation/details/screens/seriesdetails/SeriesDetailsScreen.kt
  presentation/profile/src/main/java/com/giraffe/presentation/profile/components/PosterItemHorizontal.kt
Labels: fix

#791 Fix navigation animation for RTL layouts
  presentation/home/src/main/java/com/giraffe/presentation/home/navigation/main/MainNavGraph.kt
Labels: fix

#808 Refactor/readme
  README.md
Labels: enhancement

#812 Refactor Match Pager in Match Screen
  presentation/match/src/main/java/com/giraffe/match/composable/OptionList.kt
  presentation/match/src/main/java/com/giraffe/match/composable/PageSingleSelectionTextOnly.kt
  presentation/match/src/main/java/com/giraffe/match/composable/PageWithMultiSelectionTextOnly.kt
  presentation/match/src/main/java/com/giraffe/match/screen/match_pager/MatchPagerScreen.kt
  presentation/match/src/main/java/com/giraffe/match/screen/match_pager/MatchPagerViewModel.kt
Labels: fix

#840 fix(onboarding): update padding to use systemBarsPadding for better layout
  presentation/authentication/src/main/java/com/giraffe/presentation/authentication/screens/onboarding/screen/OnBoardingScreen.kt
Labels: bug

#841 Refactor: Reorder modifiers in LoginScreen
  presentation/authentication/src/main/java/com/giraffe/presentation/authentication/screens/login/screen/LoginScreen.kt
Labels: bug

#842 Fix/hidden genre in collection details
  presentation/profile/src/main/java/com/giraffe/presentation/profile/screens/collectiondetails/CollectionDetailsViewModel.kt
Labels: bug
