Repository Rome-Squad/CineVerse-App, pull requests merged in 2025-07, with the labels that each got.

#98 Components/desin the remain components of home screen components
  designsystem/src/main/java/com/giraffe/designsystem/composable/AppBar.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/BottomNavigationBar.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/BuildingBlock.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/SectionTitle.kt
  designsystem/src/main/res/values-ar/strings.xml
  designsystem/src/main/res/values/strings.xml
Labels: Component

#143 feat: Implement hourly cache cleanup for persons
  app/build.gradle.kts
  app/src/main/java/com/giraffe/cineverseapp/CineVerseApp.kt
  app/src/main/java/com/giraffe/cineverseapp/di/databaseModule.kt
  app/src/main/java/com/giraffe/cineverseapp/ui/theme/Color.kt
  app/src/main/java/com/giraffe/cineverseapp/ui/theme/Theme.kt
  app/src/main/java/com/giraffe/cineverseapp/ui/theme/Type.kt
  app/src/main/java/com/giraffe/cineverseapp/worker/CacheCleanupWorker.kt
  datasource/local/person/src/main/java/com/giraffe/person/cleaner/PersonCacheCleaner.kt
  datasource/local/person/src/main/java/com/giraffe/person/cleaner/PersonCacheCleanerImp.kt
  datasource/local/person/src/main/java/com/giraffe/person/dao/PersonDao.kt
  domain/person/src/main/java/com/giraffe/person/entity/Person.kt
  domain/person/src/test/kotlin/com/giraffe/person/usecase/GetRecentPeopleUseCaseTest.kt
  domain/person/src/test/kotlin/com/giraffe/person/usecase/SearchByNameUseCaseTest.kt
  domain/person/src/test/kotlin/com/giraffe/person/usecase/StorePersonUseCaseTest.kt
  gradle/libs.versions.toml
  repository/person/src/main/java/com/giraffe/person/local/dto/PersonDto.kt
  repository/person/src/main/java/com/giraffe/person/remote/response/SearchPersonResponse.kt
  repository/person/src/main/java/com/giraffe/person/util/Extention.kt
  repository/person/src/main/java/com/giraffe/person/util/Mapper.kt
  repository/person/src/main/java/com/giraffe/person/util/Utils.kt
  repository/person/src/test/java/com/giraffe/person/PersonRepositoryImplTest.kt
Labels: feture

#151 Fix/search history
  app/src/main/java/com/giraffe/cineverseapp/CineVerseApp.kt
  app/src/main/java/com/giraffe/cineverseapp/MainActivity.kt
  app/src/main/java/com/giraffe/cineverseapp/di/databaseModule.kt
  app/src/main/java/com/giraffe/cineverseapp/worker/CacheCleanupWorker.kt
  datasource/local/explore/src/main/java/com/giraffe/explore/LocalExploreDataSourceImpl.kt
  datasource/local/explore/src/main/java/com/giraffe/explore/dao/ExploreSearchKeywordDao.kt
  domain/explore/build.gradle.kts
  domain/explore/src/main/java/com/giraffe/explore/repository/ExploreRepository.kt
  domain/explore/src/main/java/com/giraffe/explore/usecase/ClearSearchHistoryUseCase.kt
  domain/explore/src/main/java/com/giraffe/explore/usecase/DeleteSearchKeywordUseCase.kt
  domain/explore/src/main/java/com/giraffe/explore/usecase/GetSearchKeywordsUseCase.kt
  domain/explore/src/main/java/com/giraffe/explore/usecase/InsertSearchKeywordUseCase.kt
  domain/explore/src/test/kotlin/com/giraffe/explore/usecase/ClearSearchHistoryUseCaseTest.kt
  domain/explore/src/test/kotlin/com/giraffe/explore/usecase/DeleteSearchKeywordUseCaseTest.kt
  domain/explore/src/test/kotlin/com/giraffe/explore/usecase/GetSearchKeywordsUseCaseTest.kt
  domain/explore/src/test/kotlin/com/giraffe/explore/usecase/InsertSearchKeywordUseCaseTest.kt
  gradle/libs.versions.toml
  repository/explore/src/main/java/com/giraffe/explore/ExploreRepositoryImpl.kt
  repository/explore/src/main/java/com/giraffe/explore/datasource/local/LocalExploreDataSource.kt
  repository/explore/src/main/java/com/giraffe/explore/mapper/mapper.kt
Labels: bug

#153 feat: implement cache cleanup worker
  app/src/main/java/com/giraffe/cineverseapp/CineVerseApp.kt
  app/src/main/java/com/giraffe/cineverseapp/di/databaseModule.kt
  app/src/main/java/com/giraffe/cineverseapp/worker/CacheCleanupWorker.kt
  datasource/local/movie/src/main/java/com/giraffe/movie/cleaner/MovieCacheCleaner.kt
  datasource/local/movie/src/main/java/com/giraffe/movie/cleaner/MovieCacheCleanerImp.kt
  datasource/local/movie/src/main/java/com/giraffe/movie/dao/MovieDao.kt
  datasource/local/person/src/main/java/com/giraffe/person/cleaner/PersonCacheCleanerImp.kt
  datasource/local/person/src/main/java/com/giraffe/person/dao/PersonDao.kt
  datasource/local/series/src/main/java/com/giraffe/series/cleaner/SeriesCacheCleaner.kt
  datasource/local/series/src/main/java/com/giraffe/series/cleaner/SeriesCacheCleanerImp.kt
  datasource/local/series/src/main/java/com/giraffe/series/database/SeriesDao.kt
  repository/movie/src/main/java/com/giraffe/movie/datasource/local/cacheDto/MovieCacheDto.kt
  repository/series/src/main/java/com/giraffe/series/model/SeriesDto.kt
Labels: bug

#175 Fix/design system component
  app/src/main/java/com/giraffe/cineverseapp/di/viewModelModule.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/AppBar.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/MoviesListSection.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/SectionTitle.kt
  domain/series/src/main/java/com/giraffe/series/entity/Cast.kt
  domain/series/src/main/java/com/giraffe/series/entity/Review.kt
  domain/series/src/main/java/com/giraffe/series/entity/SeriesDetails.kt
  domain/series/src/main/java/com/giraffe/series/repository/SeriesRepository.kt
  domain/series/src/main/java/com/giraffe/series/usecase/GetSeriesDetailsUseCase.kt
  presentation/details/build.gradle.kts
  presentation/details/src/main/java/com/giraffe/details/components/AddToCollectionContent.kt
  presentation/details/src/main/java/com/giraffe/details/components/GalleryItem.kt
  presentation/details/src/main/java/com/giraffe/details/components/GallerySection.kt
  presentation/details/src/main/java/com/giraffe/details/components/IconTextBox.kt
  presentation/details/src/main/java/com/giraffe/details/components/MainDetails.kt
  presentation/details/src/main/java/com/giraffe/details/components/MainInfoCard.kt
  presentation/details/src/main/java/com/giraffe/details/components/MainInfoCardSection.kt
  presentation/details/src/main/java/com/giraffe/details/components/MainMovieDetails.kt
  presentation/details/src/main/java/com/giraffe/details/components/MainMovieOrSeriesDetails.kt
  presentation/details/src/main/java/com/giraffe/details/components/MainMoviePoster.kt
  presentation/details/src/main/java/com/giraffe/details/components/MinimizedInfoRow.kt
  presentation/details/src/main/java/com/giraffe/details/components/RatingSelector.kt
  presentation/details/src/main/java/com/giraffe/details/components/RatingStars.kt
  presentation/details/src/main/java/com/giraffe/details/components/ReadMoreText.kt
  presentation/details/src/main/java/com/giraffe/details/components/ReviewCard.kt
  presentation/details/src/main/java/com/giraffe/details/components/SeasonCard.kt
  presentation/details/src/main/java/com/giraffe/details/components/StaffInfoSection.kt
  presentation/details/src/main/java/com/giraffe/details/components/StarCastSection.kt
  presentation/details/src/main/java/com/giraffe/details/preview/PreviewDetails.kt
  presentation/details/src/main/java/com/giraffe/details/utils/getCurrentLocalDateTime.kt
  presentation/details/src/main/java/com/giraffe/details/utils/imageSourceToPainter.kt
  presentation/details/src/main/res/values-ar-rEG/strings.xml
  presentation/details/src/main/res/values/strings.xml
  repository/series/src/main/java/com/giraffe/series/SeriesRepositoryImpl.kt
Labels: fix

#178 Feature/movie details state management
  app/src/main/java/com/giraffe/cineverseapp/di/useCaseModule.kt
  domain/movies/src/main/java/com/giraffe/movies/usecase/MoviesUseCases.kt
  domain/person/src/main/java/com/giraffe/person/repository/PersonRepository.kt
  domain/person/src/main/java/com/giraffe/person/usecase/GetPeopleByMovieIdUseCase.kt
  domain/person/src/test/kotlin/com/giraffe/person/usecase/SearchPeopleByNameUseCaseTest.kt
  presentation/details/build.gradle.kts
  presentation/details/src/main/java/com/giraffe/details/.gitkeep
  presentation/details/src/main/java/com/giraffe/details/base/BaseViewModel.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/MovieDetailsEffect.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/MovieDetailsInteractionListener.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/MovieDetailsScreenState.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/MovieDetailsViewModel.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/model/MovieUi.kt
  presentation/details/src/main/java/com/giraffe/details/utils/errorToMessage.kt
  presentation/details/src/main/res/values-ar-rEG/strings.xml
  presentation/details/src/main/res/values/strings.xml
  repository/person/src/main/java/com/giraffe/person/PersonRepositoryImpl.kt
Labels: Component

#187 Hot fix For some components in details screen
  presentation/details/src/main/java/com/giraffe/details/components/ImageCard.kt
  presentation/details/src/main/java/com/giraffe/details/components/ReviewCard.kt
  presentation/details/src/main/java/com/giraffe/details/components/StarCastSection.kt
Labels: fix

#189 fix: avoid crash when typing fast in search by replacing collect with collectLatest
  presentation/explore/src/main/java/com/giraffe/explore/ExploreViewModel.kt
Labels: fix

#200 Add UI for movie details Feature
  app/src/main/java/com/giraffe/cineverseapp/di/viewModelModule.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/AppBar.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/BaseBottomSheet.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/button_type/PrimaryButton.kt
  domain/media/src/main/java/com/giraffe/media/entity/Review.kt
  domain/media/src/main/java/com/giraffe/media/movies/entity/MovieReview.kt
  domain/media/src/main/java/com/giraffe/media/movies/repository/MoviesRepository.kt
  domain/media/src/main/java/com/giraffe/media/movies/usecase/GetMovieReviewsUseCase.kt
  domain/media/src/main/java/com/giraffe/media/series/entity/SeriesReview.kt
  domain/media/src/main/java/com/giraffe/media/series/repository/SeriesRepository.kt
  domain/media/src/main/java/com/giraffe/media/series/usecase/GetSeriesReviewsUseCase.kt
  domain/media/src/test/kotlin/com/giraffe/media/movies/usecase/GetMovieReviewsUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/series/usecase/fakeSeries.kt
  presentation/details/src/main/java/com/giraffe/details/components/AddToCollectionContent.kt
  presentation/details/src/main/java/com/giraffe/details/components/MainDetails.kt
  presentation/details/src/main/java/com/giraffe/details/components/MainMovieOrSeriesDetails.kt
  presentation/details/src/main/java/com/giraffe/details/components/RatingSection.kt
  presentation/details/src/main/java/com/giraffe/details/components/ReviewCard.kt
  presentation/details/src/main/java/com/giraffe/details/components/StaffInfoSection.kt
  presentation/details/src/main/java/com/giraffe/details/components/StarCastSection.kt
  presentation/details/src/main/java/com/giraffe/details/preview/PreviewDetails.kt
  presentation/details/src/main/java/com/giraffe/details/screens/ReviewsScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/MovieDetailsScreenState.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/MovieDetailsViewModel.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/model/CastUi.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/model/CrewUi.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/model/MovieUi.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/model/ReviewUi.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/screen/MovieDetailsScreen.kt
  presentation/details/src/main/java/com/giraffe/details/utils/getCurrentLocalDateTime.kt
  presentation/details/src/main/res/drawable/due_tone_folder.xml
  presentation/details/src/main/res/drawable/main_poster_test.png
  presentation/details/src/main/res/drawable/reviewer.jpg
  presentation/details/src/main/res/values-ar-rEG/strings.xml
  presentation/details/src/main/res/values/strings.xml
  repository/media/src/main/java/com/giraffe/media/movie/mapper/MovieReviewMapper.kt
  repository/media/src/main/java/com/giraffe/media/series/SeriesRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/series/mapper/Mapper.kt
Labels: feture

#213 Refactor/image viewer
  imageviewer/src/main/java/com/giraffe/imageviewer/component/SafeIslamicImage.kt
  imageviewer/src/test/java/com/giraffe/imageviewer/ExampleUnitTest.kt
Labels: enhancement

#216 General Refactor
  app/src/main/java/com/giraffe/cineverseapp/di/databaseModule.kt
  app/src/main/java/com/giraffe/cineverseapp/di/localDataSourceModule.kt
  app/src/main/java/com/giraffe/cineverseapp/di/networkModule.kt
  app/src/main/java/com/giraffe/cineverseapp/di/repositoryModule.kt
  app/src/main/java/com/giraffe/cineverseapp/di/useCaseModule.kt
  datasource/local/media/src/main/java/com/giraffe/media/util/SafeCall.kt
  datasource/local/media/src/test/java/com/giraffe/media/series/SeriesRoomLocalDateSourceTest.kt
  datasource/remote/media/src/main/java/com/giraffe/media/movie/MoviesRemoteDataSourceImp.kt
  datasource/remote/media/src/main/java/com/giraffe/media/person/PersonRemoteDataSourceImp.kt
  datasource/remote/media/src/main/java/com/giraffe/media/person/response/PersonMovieCreditsResponse.kt
  datasource/remote/media/src/main/java/com/giraffe/media/person/response/PersonTvCastItemResponse.kt
  datasource/remote/media/src/main/java/com/giraffe/media/series/SeriesRemoteDataSourceImp.kt
  datasource/remote/media/src/main/java/com/giraffe/media/util/RequestBuilder.kt
  domain/media/src/main/java/com/giraffe/media/person/entity/Person.kt
  domain/media/src/main/java/com/giraffe/media/person/entity/PersonCredit.kt
  domain/media/src/main/java/com/giraffe/media/person/entity/PersonSocialMediaLinks.kt
  domain/media/src/test/kotlin/com/giraffe/media/person/usecase/GetPersonDetailsUseCaseTest.kt
  presentation/details/src/main/java/com/giraffe/details/components/MainDetails.kt
  presentation/details/src/main/java/com/giraffe/details/preview/PreviewDetails.kt
  presentation/details/src/main/java/com/giraffe/details/screens/castDetails/CastDetailsEffect.kt
  presentation/details/src/main/java/com/giraffe/details/screens/castDetails/CastDetailsScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/castDetails/CastDetailsViewModel.kt
  repository/media/src/main/java/com/giraffe/media/person/PersonRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/person/datasource/remote/PersonRemoteDataSource.kt
  repository/media/src/main/java/com/giraffe/media/person/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/person/model/dto/PersonCreditDto.kt
  repository/media/src/main/java/com/giraffe/media/person/model/dto/PersonMovieCastItemDto.kt
  repository/media/src/main/java/com/giraffe/media/person/model/dto/PersonSocialMediaDto.kt
  repository/media/src/main/java/com/giraffe/media/person/model/dto/PersonTvCastDto.kt
  repository/media/src/main/java/com/giraffe/media/utils/ImageUrl.kt
  repository/media/src/main/java/com/giraffe/media/utils/UrlConstants.kt
Labels: enhancement

#229 Feature/api modules explore
  api/details/src/main/java/com/giraffe/details/DetailsApi.kt
  api/explore/src/main/java/com/giraffe/explore/ExploreApi.kt
  app/src/main/java/com/giraffe/cineverseapp/AppNavigation.kt
  app/src/main/java/com/giraffe/cineverseapp/MainActivity.kt
  app/src/main/java/com/giraffe/cineverseapp/di/featureApiModule.kt
  presentation/details/src/main/java/com/giraffe/details/navigation/DetailsApiImp.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/screen/MovieDetailsScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsScreen.kt
  presentation/explore/src/main/java/com/giraffe/explore/components/CastItem.kt
  presentation/explore/src/main/java/com/giraffe/explore/components/ResultsActors.kt
  presentation/explore/src/main/java/com/giraffe/explore/components/TransitionLazyColumnToGrid.kt
  presentation/explore/src/main/java/com/giraffe/explore/nav/route/DiscoverRoute.kt
  presentation/explore/src/main/java/com/giraffe/explore/nav/route/SearchResultRoute.kt
  presentation/explore/src/main/java/com/giraffe/explore/nav/route/SearchRoute.kt
  presentation/explore/src/main/java/com/giraffe/explore/navigation/ExploreApiImp.kt
  presentation/explore/src/main/java/com/giraffe/explore/navigation/ExploreNavGraph.kt
  presentation/explore/src/main/java/com/giraffe/explore/navigation/route/DiscoverRoute.kt
  presentation/explore/src/main/java/com/giraffe/explore/navigation/route/SearchResultRoute.kt
  presentation/explore/src/main/java/com/giraffe/explore/navigation/route/SearchRoute.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/ExploreApiImp.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/discover/DiscoverScreen.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultScreen.kt
Labels: feture

#230 Feature/api modules explore
  api/details/src/main/java/com/giraffe/details/DetailsApi.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/ViewToggle.kt
  presentation/details/src/main/java/com/giraffe/details/components/recomended/RecomendedContent.kt
  presentation/details/src/main/java/com/giraffe/details/navigation/DetailsApiImp.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/screen/MovieDetailsScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsScreen.kt
Labels: bug

#244 Refactor: Update recent posters handling in SearchViewModel and related mappers
  presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreenState.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchViewModel.kt
  presentation/explore/src/main/java/com/giraffe/explore/util/Mapper.kt
Labels: bug, fix

#250 Get people media credits
  app/src/main/java/com/giraffe/cineverseapp/di/useCaseModule.kt
  datasource/remote/media/src/main/java/com/giraffe/media/person/PersonRemoteDataSourceImp.kt
  datasource/remote/media/src/main/java/com/giraffe/media/person/response/PersonCreditsResponse.kt
  domain/media/src/main/java/com/giraffe/media/person/entity/PersonCredit.kt
  domain/media/src/main/java/com/giraffe/media/person/repository/PersonRepository.kt
  domain/media/src/main/java/com/giraffe/media/person/usecase/GetPeopleMediaCreditsUseCase.kt
  domain/media/src/test/kotlin/com/giraffe/media/person/usecase/GetPeopleMediaCreditsUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/person/usecase/GetPersonDetailsUseCaseTest.kt
  repository/media/src/main/java/com/giraffe/media/person/PersonRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/person/mapper/Mapper.kt
Labels: feature

#262 Refactor: Remove unnecessary guest session creation in app initialization
  app/src/main/java/com/giraffe/cineverseapp/CineVerseApp.kt
Labels: bug

#251 Feature Login Screen UI + State Management
  app/src/main/java/com/giraffe/cineverseapp/di/viewModelModule.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/button_type/PrimaryButton.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/button_type/SecondaryButton.kt
  designsystem/src/main/res/values-ar/strings.xml
  designsystem/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  presentation/authentication/build.gradle.kts
  presentation/authentication/src/main/java/com/giraffe/authentication/.gitkeep
  presentation/authentication/src/main/java/com/giraffe/authentication/base/BaseViewModel.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/composable/LoginBody.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/composable/LogoSection.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginEffect.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginInteractionListener.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginScreen.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginState.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginViewModel.kt
  presentation/authentication/src/main/res/values-ar-rEG/strings.xml
  presentation/authentication/src/main/res/values/strings.xml
Labels: feature

#277 Fix/recommendations series screen
  app/src/main/java/com/giraffe/cineverseapp/di/viewModelModule.kt
  designsystem/src/main/java/com/giraffe/designsystem/composable/AppBar.kt
  presentation/details/src/main/java/com/giraffe/details/components/SeasonCard.kt
  presentation/details/src/main/java/com/giraffe/details/components/recomended/RecomendedContent.kt
  presentation/details/src/main/java/com/giraffe/details/models/SeriesUi.kt
  presentation/details/src/main/java/com/giraffe/details/nav/DetailsNavGraph.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/RecommendedEffect.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/RecommendedInteractionListener.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/RecommendedRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/RecommendedScreenState.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/RecommendedSeriesScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/RecommendedSeriesViewModel.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/series/ObserveScrollDirection.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/series/RecommendedInteractionListener.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/series/RecommendedSeriesContent.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/series/RecommendedSeriesEffect.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/series/RecommendedSeriesRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/series/RecommendedSeriesScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/series/RecommendedSeriesViewModel.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/series/TransitionBetweenLazyColumnToLazyVerticalGridSeries.kt
  presentation/details/src/main/java/com/giraffe/details/screens/recommended/series/temp
  presentation/details/src/main/java/com/giraffe/details/screens/seriesRecommendation/SeriesRecommendationRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesRecommendation/SeriesRecommendationScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesRecommendation/SeriesRecommendationViewModel.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsEffect.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsInteractionListener.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsViewModel.kt
  repository/media/src/main/java/com/giraffe/media/series/SeriesRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/series/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/utils/ConvertFormattedDate.kt
Labels: bug

#246 Fix Placeholder in Cast on Details and Actor Search Screens
  imageviewer/src/main/java/com/giraffe/imageviewer/component/SafeIslamicImage.kt
  presentation/details/src/main/java/com/giraffe/details/components/StarCastSection.kt
  presentation/explore/src/main/java/com/giraffe/explore/components/CastItem.kt
  presentation/explore/src/main/java/com/giraffe/explore/components/ResultsActors.kt
  repository/media/src/main/java/com/giraffe/media/person/PersonRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/person/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/utils/PersonContentType.kt
Labels: bug

#280 Fix season screen
  presentation/details/src/main/java/com/giraffe/details/screens/seasons/SeasonsScreen.kt
Labels: bug

#260 feat: Implement remote pagination for actor search results
  datasource/remote/media/src/main/java/com/giraffe/media/person/retrofit/PersonApiServiceRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/person/retrofit/PersonRemoteDataSourceImpRetrofit.kt
  domain/media/src/main/java/com/giraffe/media/entity/PagingData.kt
  domain/media/src/main/java/com/giraffe/media/person/repository/PersonRepository.kt
  domain/media/src/main/java/com/giraffe/media/person/usecase/SearchPeopleByNameUseCase.kt
  domain/media/src/test/kotlin/com/giraffe/media/person/usecase/SearchByNameUseCaseTest.kt
  presentation/explore/build.gradle.kts
  presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultScreen.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultScreenState.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultViewModel.kt
  presentation/explore/src/main/java/com/giraffe/explore/util/PagingSource.kt
  repository/media/src/main/java/com/giraffe/media/person/PersonRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/person/datasource/remote/PersonRemoteDataSource.kt
  repository/media/src/main/java/com/giraffe/media/person/datasource/remote/dto/SearchPersonDto.kt
  repository/media/src/main/java/com/giraffe/media/person/mapper/Mapper.kt
Labels: enhancement

#279 Refactor(navigation): modularize and inject APIs for Details and Explore features
  api/details/src/main/java/com/giraffe/details/DetailsApi.kt
  api/details/src/main/java/com/giraffe/details/DetailsStartDestination.kt
  api/explore/src/main/java/com/giraffe/explore/ExploreApi.kt
  app/src/main/java/com/giraffe/cineverseapp/MainActivity.kt
  app/src/main/java/com/giraffe/cineverseapp/di/featureApiModule.kt
  app/src/main/java/com/giraffe/cineverseapp/nav/AppNavigator.kt
  app/src/main/java/com/giraffe/cineverseapp/nav/AppScreen.kt
  app/src/main/java/com/giraffe/cineverseapp/nav/CineverseAppContainer.kt
  presentation/details/src/main/java/com/giraffe/details/models/ReviewUi.kt
  presentation/details/src/main/java/com/giraffe/details/nav/DetailsApiImp.kt
  presentation/details/src/main/java/com/giraffe/details/nav/DetailsNavGraph.kt
  presentation/details/src/main/java/com/giraffe/details/screens/castDetails/CastDetailsRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/castDetails/CastDetailsScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/gallery/GalleryRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/gallery/Navigator.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/screen/MovieDetailsRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/screen/MovieDetailsScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/reviewScreen/ReviewRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsScreen.kt
  presentation/explore/src/main/java/com/giraffe/explore/navigation/ExploreApiImp.kt
  presentation/explore/src/main/java/com/giraffe/explore/navigation/ExploreNavGraph.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/CastDetailsRoute.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/MovieDetailsRoute.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SeriesDetailsRoute.kt
Labels: enhancement

#291 Add Navigation For Authentication Feature
  api/authentication/build.gradle.kts
  api/authentication/src/main/java/com/giraffe/authentication/AuthenticationApi.kt
  app/build.gradle.kts
  app/src/main/java/com/giraffe/cineverseapp/di/featureApiModule.kt
  presentation/authentication/build.gradle.kts
  presentation/authentication/src/main/java/com/giraffe/authentication/login/AuthWebViewScreen.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/login/WebViewRoute.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/nav/AuthenticationApiImp.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/nav/AuthenticationNavGraph.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginEffect.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginRoute.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginViewModel.kt
Labels: feature

#299 fix: implement pagination for searchByName and update cache management for search keywords
  app/src/main/java/com/giraffe/cineverseapp/di/localDataSourceModule.kt
  app/src/main/java/com/giraffe/cineverseapp/worker/CacheCleanupWorker.kt
  datasource/local/media/src/main/java/com/giraffe/media/explore/LocalExploreDataSourceImpl.kt
  datasource/local/media/src/main/java/com/giraffe/media/explore/cleaner/KeywordsCacheCleaner.kt
  datasource/local/media/src/main/java/com/giraffe/media/explore/cleaner/KeywordsCacheCleanerImp.kt
  datasource/local/media/src/main/java/com/giraffe/media/explore/dao/ExploreSearchKeywordDao.kt
  datasource/local/media/src/main/java/com/giraffe/media/person/PersonLocalDataSourceImp.kt
  datasource/local/media/src/main/java/com/giraffe/media/person/dao/PersonDao.kt
  datasource/local/media/src/main/java/com/giraffe/media/util/SafeCall.kt
  datasource/remote/media/src/main/java/com/giraffe/media/person/response/SearchPersonResponse.kt
  datasource/remote/media/src/main/java/com/giraffe/media/person/retrofit/PersonApiServiceRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/person/retrofit/PersonRemoteDataSourceImpRetrofit.kt
  domain/media/src/main/java/com/giraffe/media/entity/PagingData.kt
  domain/media/src/main/java/com/giraffe/media/explore/entity/SearchKeyword.kt
  domain/media/src/main/java/com/giraffe/media/person/repository/PersonRepository.kt
  domain/media/src/test/kotlin/com/giraffe/media/explore/usecase/DeleteSearchKeywordUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/explore/usecase/GetSearchKeywordsUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/person/usecase/SearchByNameUseCaseTest.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchViewModel.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultViewModel.kt
  presentation/explore/src/main/java/com/giraffe/explore/util/PagingSource.kt
  repository/media/src/main/java/com/giraffe/media/explore/ExploreRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/explore/datasource/local/LocalExploreDataSource.kt
  repository/media/src/main/java/com/giraffe/media/explore/datasource/local/cacheDto/SearchKeywordCacheDto.kt
  repository/media/src/main/java/com/giraffe/media/explore/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/person/PersonRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/person/datasource/local/PersonLocalDataSource.kt
  repository/media/src/main/java/com/giraffe/media/person/datasource/local/cacheDto/PersonCacheDto.kt
  repository/media/src/main/java/com/giraffe/media/person/datasource/remote/PersonRemoteDataSource.kt
  repository/media/src/main/java/com/giraffe/media/person/mapper/Mapper.kt
Labels: enhancement

#309 fix/239-recently-viewed-search-pagination
  datasource/local/media/src/main/java/com/giraffe/media/movie/MovieLocalDataSourceImp.kt
  datasource/local/media/src/main/java/com/giraffe/media/movie/dao/MovieDao.kt
  datasource/local/media/src/main/java/com/giraffe/media/series/SeriesRoomLocalDateSource.kt
  datasource/local/media/src/main/java/com/giraffe/media/series/dao/SeriesDao.kt
  datasource/remote/media/src/main/java/com/giraffe/media/movie/retrofit/MoviesApiServiceRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/movie/retrofit/MoviesRemoteDataSourceImplRetrofit.kt
  domain/media/src/main/java/com/giraffe/media/movies/repository/MoviesRepository.kt
  domain/media/src/main/java/com/giraffe/media/movies/usecase/SearchMovieByNameUseCase.kt
  domain/media/src/main/java/com/giraffe/media/series/repository/SeriesRepository.kt
  domain/media/src/main/java/com/giraffe/media/series/usecase/SearchSeriesByNameUseCase.kt
  domain/media/src/test/kotlin/com/giraffe/media/movies/usecase/SearchMovieByNameUseCaseTest.kt
  domain/media/src/test/kotlin/com/giraffe/media/series/usecase/SearchSeriesByNameUseCaseTest.kt
  presentation/details/src/main/java/com/giraffe/details/screens/gallery/GalleryViewModel.kt
  presentation/explore/src/main/java/com/giraffe/explore/components/TransitionLazyColumnToGrid.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/discover/DiscoverScreen.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultScreen.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultScreenState.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultViewModel.kt
  presentation/explore/src/main/java/com/giraffe/explore/util/PagingSource.kt
  repository/media/src/main/java/com/giraffe/media/movie/MoviesRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/local/MoviesLocalDataSource.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/local/cacheDto/MovieCacheDto.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/remote/MoviesRemoteDataSource.kt
  repository/media/src/main/java/com/giraffe/media/movie/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/person/PersonRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/series/SeriesRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/series/datasource/local/SeriesLocalDateSource.kt
  repository/media/src/main/java/com/giraffe/media/series/datasource/local/cacheDto/SeriesCacheDto.kt
  repository/media/src/main/java/com/giraffe/media/series/mapper/Mapper.kt
  repository/media/src/main/java/com/giraffe/media/utils/ConvertFormattedDate.kt
Labels: enhancement

#326 Refactor home module dependencies
  api/home/build.gradle.kts
Labels: bug

#330 Fix authentication UI
  presentation/authentication/src/main/java/com/giraffe/authentication/composable/LoginForm.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/composable/LogoSection.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginScreen.kt
Labels: fix

#359 Fix Login navigation
  presentation/authentication/build.gradle.kts
  presentation/authentication/src/main/java/com/giraffe/authentication/nav/AuthenticationApiImp.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/nav/AuthenticationNavGraph.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/nav/route/ExploreRoute.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/nav/route/HomeRoute.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginRoute.kt
Labels: fix

#362 Refactor: Simplify Layout and Adjust Padding in LoginForm and SecondaryButton.
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginScreen.kt
Labels: fix

#367 Make `StarCastSection` visibility dependent on `castList`
  presentation/details/src/main/java/com/giraffe/details/components/StarCastSection.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/screen/SeriesDetailsContent.kt
Labels: bug

#368 Fix Issue 231 : Explore Screen Not Displayed on API 26, Navigates Directly to Search
  designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt
  presentation/explore/src/main/java/com/giraffe/explore/components/ExploreHeader.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/discover/DiscoverScreen.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/searchresult/SearchResultScreen.kt
Labels: bug

#382 Fix: Clears focus when login button is clicked in LoginForm
  presentation/authentication/src/main/java/com/giraffe/authentication/composable/LoginForm.kt
  presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginScreen.kt
Labels: fix

#427 Refactor recently viewed movies to use Flow
  datasource/local/media/src/main/java/com/giraffe/media/movie/MovieLocalDataSourceImp.kt
  datasource/local/media/src/main/java/com/giraffe/media/movie/dao/MovieDao.kt
  domain/media/src/main/java/com/giraffe/media/movies/repository/MoviesRepository.kt
  domain/media/src/main/java/com/giraffe/media/movies/usecase/GetRecentlyMoviesUseCase.kt
  domain/media/src/test/kotlin/com/giraffe/media/movies/usecase/GetRecentlyMoviesUseCaseTest.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchViewModel.kt
  presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt
  presentation/home/src/main/java/com/giraffe/home/screen/movies_list/MoviesListViewModel.kt
  repository/media/src/main/java/com/giraffe/media/movie/MoviesRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/local/MoviesLocalDataSource.kt
Labels: fix

#420 Add Authentication Data Source
  app/src/main/java/com/giraffe/cineverseapp/CineVerseApp.kt
  app/src/main/java/com/giraffe/cineverseapp/data/network/CreateRetrofitClient.kt
  app/src/main/java/com/giraffe/cineverseapp/data/network/SessionIdInterceptor.kt
  app/src/main/java/com/giraffe/cineverseapp/data/preference/DataStorePreferences.kt
  app/src/main/java/com/giraffe/cineverseapp/data/preference/SessionIdManagerImpl.kt
  app/src/main/java/com/giraffe/cineverseapp/di/databaseModule.kt
  app/src/main/java/com/giraffe/cineverseapp/di/localDataSourceModule.kt
  app/src/main/java/com/giraffe/cineverseapp/di/networkModule.kt
  app/src/main/java/com/giraffe/cineverseapp/di/repositoryModule.kt
  datasource/local/user/build.gradle.kts
  datasource/local/user/src/main/java/com/giraffe/movie/UserLocalDataSource.kt
  datasource/local/user/src/main/java/com/giraffe/user/AuthenticationLocalDataSourceImp.kt
  datasource/local/user/src/main/java/com/giraffe/user/UserLocalDataSource.kt
  datasource/local/user/src/main/java/com/giraffe/user/datastore/AuthenticationDatastore.kt
  datasource/remote/media/src/main/java/com/giraffe/media/movie/retrofit/MoviesApiServiceRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/movie/retrofit/MoviesRemoteDataSourceImplRetrofit.kt
  datasource/remote/media/src/main/java/com/giraffe/media/util/NetworkConstants.kt
  datasource/remote/user/src/main/java/com/giraffe/user/retrofit/AuthenticationRemoteDataSourceImpRetrofit.kt
  datasource/remote/user/src/main/java/com/giraffe/user/retrofit/UserRemoteDataSourceImplRetrofit.kt
  domain/user/src/main/java/com/giraffe/user/exception/AuthException.kt
  domain/user/src/main/java/com/giraffe/user/repository/AuthRepository.kt
  repository/media/src/main/java/com/giraffe/media/movie/MoviesRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/movie/datasource/remote/MoviesRemoteDataSource.kt
  repository/user/src/main/java/com/giraffe/repository/AuthRepositoryImpl.kt
  repository/user/src/main/java/com/giraffe/repository/AuthenticationRepositoryImpl.kt
  repository/user/src/main/java/com/giraffe/repository/datasource/local/AuthenticationRemoteDataSource.kt
  repository/user/src/main/java/com/giraffe/repository/datasource/remote/AuthenticationLocalDataSource.kt
  repository/user/src/main/java/com/giraffe/repository/datasource/remote/UserRemoteDataSource.kt
  repository/user/src/main/java/com/giraffe/repository/exceptions/AuthDataException.kt
  repository/user/src/main/java/com/giraffe/repository/utils/safeCall.kt
Labels: fix

#459 Translate Explore screen strings to Arabic
  presentation/explore/src/main/res/values-ar/strings.xml
Labels: bug

#460 fix/352-recently-viewed-updated-immediately
  datasource/local/media/src/main/java/com/giraffe/media/series/SeriesRoomLocalDateSource.kt
  datasource/local/media/src/main/java/com/giraffe/media/series/dao/SeriesDao.kt
  domain/media/src/main/java/com/giraffe/media/series/repository/SeriesRepository.kt
  domain/media/src/main/java/com/giraffe/media/series/usecase/GetRecentSeriesUseCase.kt
  domain/media/src/test/kotlin/com/giraffe/media/series/usecase/GetRecentSeriesGenresTest.kt
  presentation/explore/src/main/java/com/giraffe/explore/base/BaseViewModel.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchInteractionListener.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreenState.kt
  presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchViewModel.kt
  presentation/home/src/main/java/com/giraffe/home/base/BaseViewModel.kt
  presentation/home/src/main/java/com/giraffe/home/screen/home/HomeScreenUiState.kt
  presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt
  presentation/home/src/main/java/com/giraffe/home/screen/movies_list/MoviesListUiState.kt
  presentation/home/src/main/java/com/giraffe/home/screen/movies_list/MoviesListViewModel.kt
  repository/media/src/main/java/com/giraffe/media/series/SeriesRepositoryImpl.kt
  repository/media/src/main/java/com/giraffe/media/series/datasource/local/SeriesLocalDateSource.kt
Labels: fix

#458 feat: Implement login prompt for rating and add to collection
  domain/user/src/main/java/com/giraffe/user/usecase/IsLoggedInUseCase.kt
  domain/user/src/test/kotlin/com/giraffe/user/usecase/IsLoggedInUseCaseTest.kt
  presentation/details/build.gradle.kts
  presentation/details/src/main/java/com/giraffe/details/components/LoginBottomSheet.kt
  presentation/details/src/main/java/com/giraffe/details/nav/DetailsApiImp.kt
  presentation/details/src/main/java/com/giraffe/details/nav/DetailsNavGraph.kt
  presentation/details/src/main/java/com/giraffe/details/nav/route/LoginRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/MovieDetailsViewModel.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/screen/MovieDetailsRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/screen/MovieDetailsScreen.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsInteractionListener.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsScreenState.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsViewModel.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/screen/SeriesDetailsContent.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/screen/SeriesDetailsRoute.kt
  presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/screen/SeriesDetailsScreen.kt
  presentation/details/src/main/res/values-ar/strings.xml
  presentation/details/src/main/res/values/strings.xml
  repository/user/src/main/java/com/giraffe/repository/AuthenticationRepositoryImpl.kt
Labels: fix
